name: hwscontrol
description: Sistema de gerenciamento de conteúdo.

publish_to: 'none'

version: 2.0.0+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  loading_overlay_pro: ^2.1.1
  uuid: 3.0.5
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.2.0
  cloud_firestore: ^3.1.0
  firebase_database: ^9.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
