name: hwscontrol
description: Sistema de gerenciamento de conteúdo.

publish_to: 'none'

version: 2.0.0+77

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.2.0
  cloud_firestore: ^3.1.0
  firebase_database: ^9.0.3
  html: ^0.15.0
  url_launcher: ^6.0.17
  image_picker: ^0.8.4+4
  file_picker: ^4.3.0
  flutter_easyloading: ^3.0.3
  flutter_masked_text2: ^0.9.1
  date_range_form_field: ^1.0.2
  flutter_material_pickers: ^3.1.2
  syncfusion_flutter_calendar: ^19.3.59
  datetime_picker_formfield: ^2.0.0
  audioplayers: ^0.20.1
  flutter_cupertino_localizations: ^1.0.1
  dropdown_button2: ^1.0.7
  paginate_firestore: ^1.0.3
  image_cropper: ^1.4.1
  decorated_icon: ^1.2.1
  fwfh_webview: ^0.6.2+1
  flutter_widget_from_html_core: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    #- assets/json/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
